title: Garden Variety Herbs
tagline: Garden Variety Herbs
email: gardenvarietyherbs@gmail.com
description: >-
  Garden Variety Herbs band website
url: "https://gardenvarietyherbs.github.io"
author: gardenvarietyherbs
twitter:
  username: itspatrq
  card: summary
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
# Build settings
markdown: kramdown
remote_theme: ItsPatrq/minimal-music-project
permalink: /:title.html
pagination:
  enabled: true
  per_page: 4
  limit: 0
  sort_field: 'date'
  sort_reverse: true

  exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - node_modules
